CREATE TABLE `collectables` (
    `identifier` VARCHAR(255),
    `xp`             int(11) NOT NULL,
    `wisteria`       int(11) NOT NULL,
    `bitterweed`     int(11) NOT NULL,
    `creakplum`      int(11) NOT NULL,
    `cardinalflower` int(11) NOT NULL,
    `bloodflower`    int(11) NOT NULL,
    `chocolatedaisy` int(11) NOT NULL,
    `texasbluebonnet`int(11) NOT NULL,
   `aceofswords`    int(11) NOT NULL,
   `kingofswords`   int(11) NOT NULL,
   `queenofswords`  int(11) NOT NULL,
   `knightofswords` int(11) NOT NULL,
   `pageofswords`   int(11) NOT NULL, 
   `twoofswords`    int(11) NOT NULL,   
   `threeofswords`  int(11) NOT NULL, 
   `fourofswords`   int(11) NOT NULL,  
   `fiveofswords`   int(11) NOT NULL,  
   `sixofswords`    int(11) NOT NULL,   
   `sevenofswords`  int(11) NOT NULL, 
   `eightofswords`  int(11) NOT NULL, 
   `nineofswords`   int(11) NOT NULL,  
   `tenofswords`    int(11) NOT NULL, 
   `aceofcups`      int(11) NOT NULL,  
   `kingofcups`     int(11) NOT NULL,  
   `queenofcups`    int(11) NOT NULL, 
   `knightofcups`   int(11) NOT NULL,
   `pageofcups`     int(11) NOT NULL, 
   `twoofcups`      int(11) NOT NULL,   
   `threeofcups`    int(11) NOT NULL, 
   `fourofcups`     int(11) NOT NULL,  
   `fiveofcups`     int(11) NOT NULL,  
   `sixofcups`      int(11) NOT NULL,   
   `sevenofcups`    int(11) NOT NULL, 
   `eightofcups`    int(11) NOT NULL, 
   `nineofcups`     int(11) NOT NULL,  
   `tenofcups`      int(11) NOT NULL,   
   `aceofwands`     int(11) NOT NULL,   
   `kingofwands`    int(11) NOT NULL,  
   `queenofwands`   int(11) NOT NULL, 
   `knightofwands`  int(11) NOT NULL,
   `pageofwands`    int(11) NOT NULL, 
   `twoofwands`     int(11) NOT NULL,   
   `threeofwands`   int(11) NOT NULL, 
   `fourofwands`    int(11) NOT NULL,  
   `fiveofwands`    int(11) NOT NULL,  
   `sixofwands`     int(11) NOT NULL,  
   `sevenofwands`   int(11) NOT NULL, 
   `eightofwands`   int(11) NOT NULL, 
   `nineofwands`    int(11) NOT NULL,  
   `tenofwands`     int(11) NOT NULL,   
   `aceofpentacles` int(11) NOT NULL,   
   `kingofpentacles`int(11) NOT NULL,  
   `queenofpentacles` int(11) NOT NULL, 
   `knightofpentacles`int(11) NOT NULL,
   `pageofpentacles`  int(11) NOT NULL, 
   `twoofpentacles`   int(11) NOT NULL,   
   `threeofpentacles` int(11) NOT NULL, 
   `fourofpentacles`  int(11) NOT NULL,  
   `fiveofpentacles`  int(11) NOT NULL,  
   `sixofpentacles`   int(11) NOT NULL,   
   `sevenofpentacles` int(11) NOT NULL, 
   `eightofpentacles` int(11) NOT NULL, 
   `nineofpentacles`  int(11) NOT NULL,  
   `tenofpentacles`   int(11) NOT NULL 
);
--
-- Indexes for table `collectables`
--
ALTER TABLE `collectables`
ADD PRIMARY KEY (`identifier`);
